name: Onboarding Request
description: To guide new members through the onboarding process for the VA.gov Platform or VFS team.
title: Onboarding of [individual]
labels: onboarding, VFS, operations

body:
  - type: markdown
    attributes:
      value: "**Note:** this ticket should not be submitted until after you receive access to the appropriate repos. You will receive an email titled “USAccess PIV Sponsored” when your access is ready."
  - type: markdown
    attributes:
      value: "## Welcome and Introduction\nWelcome to the Department of Veterans Affairs (VA) Veteran Facing Services (VFS) team!\n\nAs a new VFS team member, you will be working in the web ecosystem we call the VA.gov Platform (or \"**The Platform,**\" for short). The tasks on this list are designed to get you up to speed on the role of Platform, making it easier for you to do your job.\n\nBecause the VA is a huge organization that serves millions, the Platforms it runs on are equally big, complex, and multilayered. Most people find that even learning the basics for their own practice area entails a significant learning curve. The tasks on this checklist will help you acquire those basics as quickly and efficiently as possible."
  - type: markdown
    attributes:
      value: "## User Story\nAs a new VFS team member, I need to complete onboarding activities so I can successfully work on my project and support the VA.gov Platform."
  - type: markdown
    attributes:
      value: "## How to fill out this ticket\n- [ ] Add your name to the ticket title\n- [ ] Complete the Onboarding Checklist below\n- [ ] Under **Get set up for your practice area,** you only need to complete the items for your role\n- [ ] You can close this ticket when all items are completed in the Onboarding Checklist and the Platform Checklist"
  - type: markdown
    attributes:
      value: "## Onboarding Checklist"
  - type: markdown
    attributes:
      value: "### Share your info with Platform"
  - type: markdown
    attributes:
      value: "- [ ] Complete the fields above"
  - type: input
    id: requiredName
    attributes:
      label: Name
      placeholder: ex. Jane Smith
    validations:
      required: true
  - type: input
    id: pronouns
    attributes:
      label: Pronouns
      placeholder: ex. she/her
    validations:
      required: false
  - type: input
    id: role
    attributes:
      label: Role
      placeholder: 
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
      placeholder: 
    validations:
      required: true
  - type: input
    id: githubHandle
    attributes:
      label: GitHub Handle
      placeholder: 
    validations:
      required: true
  - type: input
    id: startDate
    attributes:
      label: Start Date
      placeholder: MM/DD/YYYY
    validations:
      required: true
  - type: input
    id: vfsTeam
    attributes:
      label: VFS Team
      placeholder: 
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### General"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [General orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Generalorientation) recording"
  - type: markdown
    attributes:
      value: "- [ ] Update your [Slack profile](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile)"
  - type: markdown
    attributes:
      value: "- [ ] Watch [VA.gov overview video](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html#PlatformOrientation-Purpose)"
  - type: markdown
    attributes:
      value: "- [ ] Watch [VFS Orientation for Platform Website video](https://www.youtube.com/watch?v=I3RFCuTEfBI&ab_channel=PlatformCrew)"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Platform Support overview video](https://www.youtube.com/watch?v=iwIQU4XepNQ)"
  - type: markdown
    attributes:
      value: "- [ ] Review the [Getting help from the Platform in Slack guidance](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)"
  - type: markdown
    attributes:
      value: "- [ ] Review [Welcome documentation](https://depo-platform-documentation.scrollhelp.site/getting-started/Welcome.1255276574.html)"
  - type: markdown
    attributes:
      value: "- [ ] Review [Support Overview](https://depo-platform-documentation.scrollhelp.site/support/Support-overview.604012552.html) documentation"
  - type: markdown
    attributes:
      value: "- [ ] Review the guidance on [Submitting a feature request](https://depo-platform-documentation.scrollhelp.site/support/Submitting-a-feature-request.1938915400.html)"
  - type: markdown
    attributes:
      value: "- [ ] [Request Access to Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)"
  - type: markdown
    attributes:
      value: "- [ ] Confirm that you have access to the [VA GitHub Organization](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization)\n  **Note:** Membership in the VA GitHub Organization is a prerequisite for getting access to vets.gov-write and access to many commonly-used repositories. Platform will not be able to complete this task if you are not a member of the VA GitHub Organization."
  - type: markdown
    attributes:
      value: "- [ ] [Opt out of Google Analytics](https://www.va.gov/analytics-opt-out.html) on all of your browsers on your work machines, personal machines (if you are not a Veteran yourself using the site for your own applications), and mobile devices"
  - type: markdown
    attributes:
      value: "### Norms and Standards"
  - type: markdown
    attributes:
      value: "- [ ] Review guidance on the [Platform Satisfaction Survey](https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey)"
  - type: markdown
    attributes:
      value: "### Working on the Platform"
  - type: markdown
    attributes:
      value: "- [ ] Review the [Platform Principles](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-crew-principles)"
  - type: markdown
    attributes:
      value: "- [ ] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub"
  - type: markdown
    attributes:
      value: "- [ ] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/digitalmodernizationstrategy.pdf)"
  - type: markdown
    attributes:
      value: "- [ ] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/the-new-va.gov-briefing-2019-07.pdf) documentation"
  - type: markdown
    attributes:
      value: "- [ ] Review the [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) documentation on Platform Website"
  - type: markdown
    attributes:
      value: "- [ ] Are you a Veteran? Consider adding your name to the [Veterans willing to help VA teams with product testing](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) document"
  - type: markdown
    attributes:
      value: "### Get set up for your practice area"
  - type: markdown
    attributes:
      value: "#### Designers & Researchers"
  - type: markdown
    attributes:
      value: "- [ ] Review the [Research and Design Guide on Platform Website](https://depo-platform-documentation.scrollhelp.site/research-design/index.html)"
  - type: markdown
    attributes:
      value: "- [ ] Learn how we do [research at VA](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va)"
  - type: markdown
    attributes:
      value: "- [ ] Get oriented to the [Design System](https://design.va.gov/)"
  - type: markdown
    attributes:
      value: "- [ ] Get oriented to the [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Design orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Design&ResearchOrientation) recording"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Accessibility orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-AccessibilityOrientation) recording"
  - type: markdown
    attributes:
      value: "#### Front-end Engineers"
  - type: markdown
    attributes:
      value: "- [ ] Review [frontend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-developer-documentation.687931428.html) on Platform Website"
  - type: markdown
    attributes:
      value: "- [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Front-end orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Front-endorientation) recording"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Analytics orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-AnalyticsOrientation) recording"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Accessibility orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Accessibilityorientation) recording"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [QA orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAOrientation) recording"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Design System/Forms Library orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Designsystem/formslibraryorientation) recording"
  - type: markdown
    attributes:
      value: "#### Back-end Engineers"
  - type: markdown
    attributes:
      value: "- [ ] Review [back-end developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Backend-developer-documentation.1886289964.html) on Platform Website"
  - type: markdown
    attributes:
      value: "- [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Back-end orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Back-endOrientation) recording"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [QA orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAOrientation) recording"
  - type: markdown
    attributes:
      value: "#### Product Managers & Delivery Managers"
  - type: markdown
    attributes:
      value: "- [ ] [Schedule a PM intro via Calendly](https://calendly.com/collaboration-cycle/product-manager-intro) with Shira Goodman (Platform Governance Team PM)."
  - type: markdown
    attributes:
      value: "- [ ] If your team is new, please complete the [New VFS Team ticket](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members#Guidancefornewteamsandteammembers-NewVFSteams). If you're joining an existing team, you can skip this step."
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Analytics orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-AnalyticsOrientation) recording"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [Accessibility orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-AccessibilityOrientation) recording"
  - type: markdown
    attributes:
      value: "- [ ] Watch the [QA orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAorientation) recording"
  - type: markdown
    attributes:
      value: "### Off-boarding of teammates"
  - type: markdown
    attributes:
      value: "- [ ] Review [process for when a teammate leaves](https://depo-platform-documentation.scrollhelp.site/getting-started/offboarding)"
  - type: markdown
    attributes:
      value: "## Platform Checklist"
  - type: markdown
    attributes:
      value: "The items in this checklist are for Platform to complete. If you are ready to close the ticket and the Platform Checklist section has not been completed, please reach out to Platform via the guidance provided in [Getting help from Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)."
  - type: markdown
    attributes:
      value: "- [ ] New VFS team member has been added to the VFS Team Roster located in [Atlas](https://www.va.gov/atlas/)"
  - type: markdown
    attributes:
      value: "- [ ] New VFS team member has been added to the vets.gov-write GitHub team"
