name: Offboarding Request Form
description: |
  Fill out the name of the individual and the **Description** section below. Note: This form only handles deactivation from the DSVA (Office of CTO @ VA) Slack instance. For Lighthouse Slack and other DOTS-managed tool removal, please submit a [ticket for DOTS removal](https://jira.devops.va.gov/servicedesk/customer/portal/1/create/714).

  *(Please add only one individual per form)*

title: Offboarding Request for ${{ inputs.name }}

inputs:
  - name: Individual's Name
    description: "Enter the name of the individual being offboarded"
    required: true
    type: string

  - name: Team Name
    description: "Enter the team name"
    required: false
    type: string

  - name: Role on Team
    description: "Enter the individual's role on the team"
    required: false
    type: string

  - name: Expected Last Day
    description: "Enter the expected last day (MM/DD/YYYY)"
    required: true
    type: string

  - name: Company They Work For
    description: "Enter the company they work for"
    required: false
    type: string

  - name: Email
    description: "List relevant emails (VA, Company, Personal, etc.)"
    required: true
    type: string

  - name: GitHub Username
    description: "Enter the GitHub username (include @ symbol)"
    required: false
    type: string

  - name: COR
    description: "Enter the Contracting Officer Representative (if applicable)"
    required: false
    type: string

  - name: PM
    description: "Enter the Project Manager (if applicable)"
    required: false
    type: string

  - name: Additional Access
    description: "List any additional access titles"
    required: false
    type: textarea

body: |
  ## Platform Support Tasks

  _The following steps are performed by the **Platform Support Tier 1** team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3105554515/Tier+1+Offboarding+Responsibilities)_

  - [ ] Requested removal from DSVA Slack
  - [ ] Requested removal from Confluence
  - [ ] Remove from Platform Atlas
  - [ ] User removed from VA GitHub Org
  - [ ] PagerDuty access removed
  - [ ] Sentry access removed
  - [ ] TestRail access removed
  - [ ] Zenhub license removed
  - [ ] Okta account disabled

footer: |
  :raised_hands: :tada: All done. Don't fill out or modify anything below here. :tada: :raised_hands:
