name: Offboarding Request Form
description: |
  Fill out name of individual and **Description** section below. Note: This form only handles deactivation from the DSVA (Office of CTO @ VA) Slack instance. For Lighthouse Slack and other DOTS-managed tool removal, please submit a [ticket for DOTS removal](https://jira.devops.va.gov/servicedesk/customer/portal/1/create/714).
  
  *(Please add only one individual per form)*

fields:
  - name: Individual's Name
    type: text
    required: true

  - name: Team Name
    type: text
    required: true

  - name: Role on Team
    type: text
    required: true

  - name: Expected Last Day
    type: date
    required: true
    format: MM/DD/YYYY

  - name: Company They Work For
    type: text
    required: true

  - name: Email
    type: text
    required: true
    description: 'Multiple emails listed in order of relevance to VA business, VA, Company, Personal, etc.'

  - name: GitHub Username
    type: text
    required: true
    description: 'Please include @ symbol'

  - name: COR
    type: text
    required: true

  - name: PM
    type: text
    required: true

  - name: Additional Access
    type: textarea
    required: false
    description: 'First line formatted with access titles only. Additional notes may be added on second line after the list.'

platform_support_tasks:
  title: Platform Support Tasks
  description: |
    _The following steps are performed by the **Platform Support Tier 1** team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/3105554515/Tier+1+Offboarding+Responsibilities)_

  tasks:
    - name: Requested removal from DSVA Slack
      type: checkbox
      description: 'Search for them in Slack'
      required: false

    - name: Requested removal from Confluence
      type: checkbox
      required: false

    - name: Remove from Platform Atlas
      type: checkbox
      required: false

    - name: User removed from VA GitHub Org
      type: checkbox
      required: false

    - name: Pagerduty access removed
      type: checkbox
      required: false

    - name: Sentry access removed
      type: checkbox
      required: false

    - name: TestRail access removed
      type: checkbox
      required: false

    - name: Zenhub license removed
      type: checkbox
      required: false

    - name: Okta account disabled
      type: checkbox
      required: false

footer: |
  :raised_hands: :tada: All done. Don't fill out or modify anything below here. :tada: :raised_hands:
